-- user
INSERT INTO USER (USER_ID, PASSWORD) VALUES ('admin', 'pass');

-- word
INSERT INTO VOCABULARY_BOOK (ID, WORD, MEANING) VALUES ('1', '1', 'hoge');
INSERT INTO VOCABULARY_BOOK (ID, WORD, MEANING) VALUES ('2', '2', 'hoge');
INSERT INTO VOCABULARY_BOOK (ID, WORD, MEANING) VALUES ('3', '3', 'hoge');
INSERT INTO VOCABULARY_BOOK (ID, WORD, MEANING) VALUES ('4', '4', 'hoge');
INSERT INTO VOCABULARY_BOOK (ID, WORD, MEANING) VALUES ('5', '5', 'hoge');
