-- user
DROP TABLE IF EXISTS USER;
CREATE TABLE USER (
  USER_ID        VARCHAR(30) NOT NULL,
  PASSWORD    VARCHAR(100) NOT NULL,
  PRIMARY KEY (USER_ID)
);

-- VOCABULARY_BOOK(English Words and Meanings)
DROP TABLE IF EXISTS VOCABULARY_BOOK;
CREATE TABLE VOCABULARY_BOOK (
 ID VARCHAR(30) NOT NULL,
 WORD VARCHAR(15) NOT NULL,
 MEANING VARCHAR(40) NOT NULL,
 PRIMARY KEY (ID)
);

